### ISSUE TITLE
Problems with the input deck specification in the EPOCH user manual

### ISSUE THREAD

**Issue by TobiasZawada** [andsunds/epoch-mode#1]
Hi, I am Tobias from [emacs.stackexchange.com](https://emacs.stackexchange.com/questions/45526/create-a-command-or-key-binding-for-closing-code-blocks).

There are several problems with the input deck specification in the EPOCH manual which are critical for `epoch-mode`. I don't have EPOCH. So, if you want those problems resolved, you should test the program.

Quote from Section 3:
> The input deck is a structured file which is split into separate blocks, with each block containing
several “parameter” = “value” pairs. The pairs can be present in any order, and not all possible
pairs must be present in any given input deck

Nothing is stated about line ends being syntactically relevant here and -- if I didn't just miss it -- nowhere else.
So in terms of the specification it would be possible that two or more “parameter” = “value” pairs occur on the same line and/or are intercepted by linebreaks. Also a line with a beginning and an end of a block could be supplemented by parts of “parameter” = “value” pairs.
That remains to be clarified.

There is also no specification of valid parameter names in general. What sequences of characters/numbers can be expected as parameter names? That is particularly important since the user can define his own constants and expressions in the `constant` block.

> import:filename - Includes another file (called filename) into the input deck...

Under Linux, file names can contain almost any character including `#` and `\`. What happens to those file names? Are they truncated at the (quasi) comment characters?

> stop at walltime file - String parameter controlling automatic halting of the code... The default is an empty string.

That is the first notion of a string type in the specification. There is no explicit description of that type anywhere in the specification.
- Are there any delimiters?
- Are there any escape characters that would escape `\` and `#` in the string?

The comment syntax is also not clear.
What happens to lines like:

`... # \ ...`

On one hand the spec says that characters after `#` on the same line are ignored. On the other hand it says that `\` **anywhere** on the line causes line continuation with truncation of the current line.
Does that mean that the next line is still a comment and is therefore ignored??

**Comment by andsunds** [comment]
Hi Tobias,
I see your point and I agree that the code is poorly documented. Unfortunately, I'm just a simple user. The EPOCH code is not openly accessible, but it is freely available by joining the EPOCH group (takes a few days). I am not a developer or affiliated with the development team at all, but to answer your questions as best as I can:

- I believe that line ends are syntactically important.
- I don't know what happens to naughty filenames. 
- The typing is horrible. The code is supposed to be in SI units (for the experimental physicists), meaning that `charge=-1.0` has a completely different unit/type from `mass=1.0`.
- I don't know of any delimiters or escape characters.

In general the code is written by physicists for physicists, so I guess that the developers have some hope that users "know what they're doing".

My supervisor wants me to learn and use this software to do plasma physics simulations. That's where the idea behind creating a major mode to highlight some keywords, help with indentation, etc. was born. In the end, I'm also doing this project to learn some Elisp.

**Comment by TobiasZawada** [comment]
I suggest two steps to improve your `epoch-mode`:
1. File a documentation bug report for EPOCH. The document [obtaining_epoch.pdf](http://www.ccpp.ac.uk/epoch/obtaining_epoch.pdf) says you can register and login to the EPOCH gitlab and filing a bug report should be done via the issue tracker there.
2. Explore the above issues through running EPOCH with appropriate test cases. (I will add a further point about valid parameter names in my [first comment](https://github.com/andsunds/epoch-mode/issues/1#issue-373702215).)

I will open a new issue to discuss your actual problem of [closing code blocks](https://emacs.stackexchange.com/questions/45526/create-a-command-or-key-binding-for-closing-code-blocks). Nevertheless -- as you can guess -- this issue has actually direct influence on that problem.

**Comment by andsunds** [comment]
I will report the bug and try to explore as much as I can. For now though, I will work as if only "nice" input is provided by the user.

EDIT:
I should also point out that the [user manual](http://www.ccpp.ac.uk/epoch/epoch_user.pdf) which Tobias has found is not the latest version (hidden under the closed [EPOCH](https://cfsa-pmw.warwick.ac.uk/) group). So potential changed due to me reporting this issue to the developers, might not show up publicly.
