### ISSUE TITLE
Closing code blocks

### ISSUE THREAD

**Issue by TobiasZawada** [andsunds/epoch-mode#2]
From my perspective closing code blocks should work with a simple regexp-search (`re-search-backward`) and some additional simple tests.

Assumptions:
- The character sequences of valid parameter names is clear, e.g., the Fortran convention:
   `[[:alpha:]][[:alnum:]_]+`
- Parameter names may not start with `begin:` That is clear from the first assumption if that is confirmed.
- There is at most one parameter-expression pair or syntactic element of code blocks (i.e., `\(begin\|end\):[[:alpha:]]+` on one logical line.
- Code blocks do not nest, i.e., there is no code block within a code block.

Strategy:
- Save original point position with `save-excursion`.
- Search backward via regexp `^\([[:space:]]*\)begin:\([[:alpha:]][[:alnum:]_]+\)`.
- Handle line continuation on the preceding lines, i.e., as long as contiguous preceding lines contain `\` concatenate truncated versions of them as strings.
- Is the resulting string still a block beginning? If so go to the end of line starting at the original position and insert `\n\1end:\2`.

**Comment by andsunds** [comment]
Thank you! 
I now have a working (but still rough) function for closing code blocks.

Although, I never got the `\\([[:alpha:]][[:alnum:]_]+\\)` part to work while `\\([a-z][a-z0-9_]+\\)` does work for some reason.

Also, I had to have

    (string-match block-begin-regexp (thing-at-point 'line t))
    ;;The two matched groups are then saved to variables
    (setq block-indent (match-string 1 (thing-at-point 'line t))) ;indentation level of begin
    (setq block-type (match-string 2 (thing-at-point 'line t))) ;the block type

in order to extract the two group matchings. The first line seems a bit unnecessary to me since I used the same regex in `looking-at` when finding the corresponding `begin:...`. Is there something that I've misunderstood here?

**Comment by andsunds** [comment]
Once again, thank you!

There does however seem to be one bug in your code: If you try to close a code block while standing on 
a logical line after a continuation, the `epoch-close-block` freezes. 

Minimal example:

    begin:qed
    a-line-\
       which-is-continued
if you try to run `epoch-close-block` (`C-c ]`) while standing on the line "`which-is-continued`", Emacs freezes.

**Comment by andsunds** [comment]
I think that I might have tracked down the bug to `epoch-forward-logical-line`, and I believe that changing an `or` to `and` on line 157 did the trick.

I am however not 100% sure about exactly how each step in there works. I would be grateful if you (@TobiasZawada) could take an extra look before I close this issue.

**Comment by TobiasZawada** [comment]
Replacing `or` by `and` on line 157 is not the cure. With that change point remains on the last visual line of the logical line. That is not the intention. It should go to the beginning of the next logical line.
I introduced that problem by shifting the `forward-line` from the body of the `while` loop into the condition to have the `forward-line` before `cl-incf`. I did a similar change in the `N>0` case. But there I skip visual lines of one logical line through a `while` loop within the condition. Maybe we can make a macro of that kind to unify the handling. Lets see.

**Comment by TobiasZawada** [comment]
I saw the debug messages you inserted.
I do that very seldom. Usually you work with `edebug`. You can instrument a function for debugging with the menu item <kbd>Emacs-lisp</kbd>-><kbd>Instrument Function for Debugging</kbd>. It has the keybinding <kbd>C-u C-M-x</kbd>. If you call the function afterwards you can easily step through the function by tabbing the space-bar.

**Comment by andsunds** [comment]
Alright, seems like everything is working as is should. Thanks again for the help!
