### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by andsunds** [andsunds/epoch-mode#7]
Since this little side project now has grown far beyond what I had imagined a couple of days ago, I now feel that maybe some day in the future I will publicly "market" this plugin to the ~1000 scientists in the EPOCH user group. But before that, I should do some house keeping. 

When I first uploaded this project to GitHub, I just added the GPL v3 and a minor "boiler plate" copyright comments to `epoch-mode.el` (adding myself as the copyright holder). However, by now most of the code has actually be written by @TobiasZawada. Should I therefore also add him as one of the copyright holders?

**Comment by andreas-roehler** [comment]
This is a really tricky legal question. Just avoiding such notice seems an option. Ownership resp. authors right is etablished by commit - publishing it here will also have legal consequences. AFAIU things are ruled by the legal frame of this platform and the license given by the initial author.

**Comment by andsunds** [comment]
Okay, however AFAIU a copyright notice is required for the copyright holders to actually licence the code under [GPL](https://www.gnu.org/licenses/gpl-howto.html). The same link also states that all contributors have to be listed in the copyright notice, so I guess that answered my question.

**Comment by TobiasZawada** [comment]
@andsunds I didn't really care;-).
Good luck with your project.
